title: Azure Vaultwarden
description: Deploy Vaultwarden (Bitwarden-compatible server) on Azure App Service with all necessary supporting infrastructure.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

baseurl: /azure-vaultwarden

exclude:
  - README.md
